version: "3.8"
services:
  chatbot_dashboard_api:
    image: chatbot_dashboard_api:latest
    ports:
      - "8002:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres} # Default user is postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres} # Default password is postgres
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost} # Default host is localhost
      POSTGRES_PORT: ${POSTGRES_PORT:-5432} # Default port is 5433
      POSTGRES_DB: ${POSTGRES_DB:-dashboard} # Default database is dashboard
      POSTGRES_URL: postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/{POSTGRES_DB:-dashboard} # This is the URL for the Postgres database
