"""update

Revision ID: 15197427e55c
Revises: 32577f350b45
Create Date: 2025-05-22 13:21:53.446786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15197427e55c'
down_revision = '32577f350b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.alter_column('parent_message_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_message_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('parent_message_id')

    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.alter_column('parent_message_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
